name: NGBM
description: NGBM

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: '^0.5.3+4'
  url_launcher: '^5.1.3'
  zoomable_image: '^1.3.1'
  http: '^0.11.3+12'
  firebase_messaging: '^5.1.6'
  firebase_database: '^3.0.7'
  firebase_auth: '^0.14.0+5'
  #video_launcher: '^0.3.0'
  path_provider: '^1.3.0'
  audioplayer: "^0.5.2"
  webview_flutter: ^0.3.14+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - img/banner/banner1.png
    - img/banner/banner2.png
    - img/social/fb.png
    - img/social/twitter.png
    - img/social/yt.png
    - img/social/insta.png
    - img/home/crowd.jpg
    - img/home/bible.jpg
    - img/home/texting.jpg
    - img/home/lady.jpg
    - img/mis/about.png
    - img/mis/maps1.png
    - img/mis/map_icon.png
    - img/mis/phone.png
    - img/mis/email.png
    - img/mis/logo.jpg
    - img/mis/logo.gif
    - img/mis/give_online.jpg
    - img/mis/give_text.jpg
    - img/mis/demand.jpg
    - img/mis/laptop.jpg
    - img/mis/pray.jpg
    - img/mis/mic.jpg
    - img/mis/pastor.jpg
    - img/mini/tent.jpg
    - img/mini/academy.jpg
    - img/mini/health.jpg
    - img/mini/men.jpg
    - img/intro/N.png
    - img/intro/G.png
    - img/intro/B.png
    - img/intro/M.png
    - img/intro/globe.png
    - img/intro/glow.png
    - img/intro/bethel.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
